server:
  port: 8088
#spring
spring:
  datasource:                   #mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.50.74:3306/mes?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Muyuer1986
    hikari:
      max-lifetime: 500000
  jackson:                     #时间格式化
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  redis:
    host: 192.168.50.96 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
#mybatis配置逻辑删除
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    call-setters-on-nulls: true   #配置返回结果集为空时仍返回字段

#fastDFS配置
FastDFS:
  imgPrefixPath: http://120.27.244.176/
  propertiesPath: /D:/config/fastdfs.properties

#oss配置
Oos:
  accessKeyId: LTAI4FoAmdJuwmE5Q6RHffBc
  accessKeySecret: pMWwp6eiqGrnPTYqk2aHn8Q4AVheTs
  bucketName: idse-oss
  endpoint: oss-cn-hangzhou.aliyuncs.com
  filedir: image/

#nginx文件上传路径
nginx:
  filePath: E:\file/
  filePathForDownload: E:\file/download/
  ipAndPortAndFilePrefix: 192.168.50.96:80/file/

zhaoIpAndPort: 192.168.50.97:8003
liIpAndPort: 192.168.61.202:8082