server:
  port: 8088
#spring
spring:
  datasource:                   #mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.27.244.176:3306/demo?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: HBQ521521cf*
    hikari:
      max-lifetime: 500000
  jackson:                     #时间格式化
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  redis:
    host: 120.27.244.176 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: HBQ521521cf* # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
#mybatis配置逻辑删除
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    call-setters-on-nulls: true   #配置返回结果集为空时仍返回字段

#fastDFS配置
FastDFS:
  imgPrefixPath: http://120.27.244.176/
  propertiesPath: /D:/config/fastdfs.properties

#oss配置
Oos:
  accessKeyId: LTAI4FoAmdJuwmE5Q6RHffBc
  accessKeySecret: pMWwp6eiqGrnPTYqk2aHn8Q4AVheTs
  bucketName: idse-oss
  endpoint: oss-cn-hangzhou.aliyuncs.com
  filedir: image/

nginx:
  filePath: /file/
  filePathForDownload: /file/download/
  port: 8000