server:
  port: 8088

#spring
spring:
  datasource:                   #mysql
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:p6spy:mysql://service.cf:3306/demo?useUnicode=true&characterEncoding=UTF-8
          username: root
          password: HBQ521521cf*
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        slave:
          url: jdbc:p6spy:mysql://service.cf:3306/demo?useUnicode=true&characterEncoding=UTF-8
          username: root
          password: HBQ521521cf*
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      max-lifetime: 500000
  jackson:                     #时间格式化
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  redis:
    host: service.cf # Redis服务器地址
    database: 8 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: HBQ521521cf* # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  servlet:
    multipart:
      max-file-size: -1
      maxRequestSize: -1

#mybatis配置逻辑删除
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    call-setters-on-nulls: true   #配置返回结果集为空时仍返回字段

#fastDFS配置
FastDFS:
  imgPrefixPath: http://120.27.244.176/
  propertiesPath: /D:/config/fastdfs.properties

#阿里云oss配置
Oos:
  accessKeyId: LTAI4FoAmdJuwmE5Q6RHffBc
  accessKeySecret: pMWwp6eiqGrnPTYqk2aHn8Q4AVheTs
  bucketName: idse-oss
  endpoint: oss-cn-hangzhou.aliyuncs.com
  filedir: image/

#七牛云oss配置
QiNiuOos:
  ACCESS_KEY: _X-yKzkCDsq7E9VLjvXd-Bao3VlS3UpMKH__4r1_
  SECRET_KEY: IX2MSKiKVASuMfINOvWg134I_HpCRhnfFydH6TDg
  BUCKET_NAME: my-new-file
  DOMAIN: http://file.huijia21.com

#nginx文件上传路径
nginx:
  filePath: D:\file/
  filePathForDownload: D:\file/download/
  ipAndPortAndFilePrefix: 192.168.61.101:80/file/

#shiro配置
shiro:
  session-timeout: 86400000 #1天
  session-id-cookie: DEMO_COOKIE

#输出日志位置
log:
  url: C:/logs/demo

#minio文件服务
minio:
  endpoint: https://minio.huijia.cf/
  accessKey: admin
  secretKey: HBQ521521cf*
  bucketName: file

elasticsearch:
  host: es.tinggeili.checheguanjia.com
  port: 80
  username: tinggeili
  password: tinggeili